[colors.bright]
black = "0x5c6370"
blue = "0x9ecef5"
cyan = "0x7fc8d1"
green = "0xbad7a5"
magenta = "0xddaeeb"
red = "0xeca3a8"
white = "0xffffff"
yellow = "0xdfba96"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"

[window]
dynamic_padding = true
opacity = 0.8

[keyboard]
bindings = [
   { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]
