vim.keymap.set('n', 'mi', 'ysiw*e', { remap = true })
vim.keymap.set('n', 'mI', 'ds*', { remap = true })
vim.keymap.set('n', 'mb', 'ysiw*l.e', { remap = true })
vim.keymap.set('n', 'mB', 'ds*.', { remap = true })
vim.keymap.set('n', 'ms', 'ysiw~l.e', { remap = true })
vim.keymap.set('n', 'mS', 'ds~.', { remap = true })
vim.keymap.set('n', 'mc', 'ysiw`e', { remap = true })
vim.keymap.set('n', 'mC', 'ds`', { remap = true })
